### ISSUE TITLE
Create a docker container

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/obelix#11]

**Comment by frecar** [comment]
This is a good idea, I will create one :)

**Comment by ddaze** [comment]
Already working on it :)

**Comment by frecar** [comment]
Ah, that's great! :)

**Comment by egabancho** [comment]
Should we close this? See https://github.com/inveniosoftware/obelix/pull/21

In the future we should be more careful when merging so we add the proper labels to the commit messages ....

**Comment by frecar** [comment]
Yes, we should close this.
