### ISSUE TITLE
Add some sort of commit message and static code quality check

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/obelix#12]
- For commit messages we already have [kwalitee](http://github.com/inveniosoftware/kwalitee)
- For static code analysis seems like FindBugs, PMD and Checkstyle are the most popular ones (http://stackoverflow.com/questions/97599/static-analysis-tool-recommendation-for-java, http://stackoverflow.com/questions/4080/what-code-analysis-tools-do-you-use-for-your-java-projects) Although http://www.qulice.com/ looks nice

**Comment by frecar** [comment]
I am pro static code analysis, I will take a look at what is suitable and add it!

**Comment by frecar** [comment]
https://github.com/inveniosoftware/obelix/pull/16
